003 header
Hugo-NF/farmacia-de-bolso pull request #17
Opened 2021-04-24 23:56 UTC by victoragcosta

## Descrição

Adicionado Header no main layout e criação de componentes que permitem isso

## Motivation and Context

Closes #3 

## Como as mudanças foram testadas?

Rodei no modo de desenvolvimento e vi se o visual era parecido com o layout e se as coisas reagiam de uma forma legal

## Screenshots (se aplicável):
![WhatsApp Image 2021-04-24 at 20 54 56](https://user-images.githubusercontent.com/20365283/115975951-79ce0680-a53f-11eb-908c-210847cb6f6b.jpeg)

## Tipo de modificação

- [ ] Bug fix (modificações que corrigem um bug)
- [ ] Feature (modificações que adicionam uma nova funcionalidade)
- [ ] Breaking change (fix ou feature que faz com que funcionalidade(s) já existente(s) não funcione(m) como esperado)

## Checklist:

- [x] Código segue os padrões de estilo do projeto, ou seja, ESLint executa sem erros ou warnings.
- [ ] A documentação com o Swagger foi atualizada com as modificações.
- [ ] Foram adicionados testes do Jest que cobrem essa modificação.

2021-04-29 15:32 UTC, 01oseluiz requested changes

2021-04-29 15:32 UTC, 01oseluiz commented on src/components/Header/styles.ts
> +    margin-bottom: 20px;
Sugiro adicionar as linhas:

    padding-bottom: 20px;
    background-color: #ffffff;

para corrigir o background diferente. Ou então definir um background global para branco também

2021-04-29 15:44 UTC, 01oseluiz requested changes
No meu celular o título não aparece completo:
![image](https://user-images.githubusercontent.com/24704584/116579365-b35c9400-a8e8-11eb-996a-fa788ced8566.png)

2021-04-29 18:37 UTC, 01oseluiz requested changes
O header permanece fixo com o scroll.
Era esperado que ele movesse junto

2021-05-11 11:23 UTC, victoragcosta commented
> O header permanece fixo com o scroll.
> Era esperado que ele movesse junto

@01oseluiz em qual página dá para ver isso?

2021-05-11 19:00 UTC, victoragcosta commented
> No meu celular o título não aparece completo:
> ![image](https://user-images.githubusercontent.com/24704584/116579365-b35c9400-a8e8-11eb-996a-fa788ced8566.png)

não é para acontecer isso, o título pode usar toda a largura possível. Única coisa que fiz foi colocar um \n para o de bolso ser obrigado na próxima linha

2021-05-11 19:57 UTC, victoragcosta commented on src/components/Header/styles.ts
> +    margin-bottom: 20px;
Corrigi cor no último commit

2021-05-12 01:58 UTC, 01oseluiz commented
@victoragcosta, a cor de fundo ficou ok aqui, mas o texto ainda quebra.
Isso na tela de login.
Nas outras também ocorre isso, pode ser treta do meu celular.
É como se ele quebrasse a palavra em letras e por conta disso a linha de baixo some. Porém como você mesmo disse, o tamanho do texto era para ser a tela toda, e aqui sobra tela conforme o print. Não sei como resolver aqui, verifique se mais ninguém tem esse problema, vou aprovar a PR, mas recomendo deixar isso anotado.

2021-05-12 02:18 UTC, 01oseluiz approved these changes

2021-05-12 02:18 UTC, merged